---
- name: wireshark_challenge deployment playbook
  hosts: all
  sudo: yes

  roles:
    - common
    - nginx
    - ctfd 
    - async

  post_tasks:
    - name: wireshark_challenge deployment complete
      debug: msg="Visit https://{{ ansible_default_ipv4.address }} to begin the wireshark_challenge CTF"