---
- name: wireshark_challenge deployment playbook
  hosts: all
  sudo: yes

  roles:
    - common
    - nginx
    - ctfd 
    - async

  post_tasks:
    - name: playbook deployment complete
      debug: msg="Visit https://{{ ansible_fqdn }} to begin the wireshark_challenge"