---
- name: run apt-get update
  apt: update_cache=yes cache_valid_time=3600

- name: install required packages using apt-get
  apt: name="{{ item }}" state=present
  with_items:
   - nginx
   - build-essential
   - python-dev
   - python-pip
   - libffi-dev
  when: ansible_os_family == "Debian"

- name: copy pip requirements to server
  copy: src=requirements.txt dest=/tmp/requirements.txt

- name: pip install dependencies
  pip: requirements=/tmp/requirements.txt
  when: ansible_os_family == "Debian"